### ISSUE TITLE
Where's the source of this blog?

### ISSUE THREAD

**Issue by Haroenv** [bahmutov/blog#3]
I think that this is built from somewhere, but can't find the source. 

Anyway, in the (nice) article about renovate, there's a wrong syntax for a markdown link: `[Travis cron job][../slow-updates/]`, which should've been `[Travis cron job](../slow-updates/)`. I wanted to make a PR, but didn't know where to do it.

**Comment by bahmutov** [comment]
Hi @Haroenv thanks for noticing and taking time to open an issue, I appreciate this. I keep my source private because I have a lot of code experiments there, so only the final static website result is public. But I have fixed the link and deployed it, so it should be better now:)

**Comment by Haroenv** [comment]
Perfect 👌
